version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    working_directory: ~/service-zerocater
    docker:
      - image: circleci/node:8.15.1-jessie
    steps:
      - checkout
      - run:
          name: Update npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: |
            mkdir coverage
            ./node_modules/.bin/nyc report --reporter=text-lcov > coverage/lcov.info
      - store_artifacts:
          path: coverage
          prefix: coverage
